apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-as-code-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio/build-templates-bundle:93dac682ee16a08634d593b836758e1d4fa8d967
  pipelineSpec:
    params:
      - name: git-url
        value: 'https://github.com/redhat-appstudio/application-service'
      - name: revision
        value: $(git-revision)
      - name: output-image
        value: 'quay.io/redhat-appstudio/application-service:$(git-revision)'
      - name: path-context
        value: .
      - name: dockerfile
        value: Dockerfile
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: app-studio-default-workspace
      subPath: application-service-$(git-revision)